# existing base image
FROM alpine:3.22.2

# download & install dependencies & libraries
RUN apk add --update gcc
RUN apk --update add redis

# start-up instruction for container
CMD [ "redis-server" ]